name: Build Windows x64 Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 pdf2image dashscope Pillow pyinstaller
        
    - name: Download Poppler
      run: |
        $url = "https://github.com/oschwartz10612/poppler-windows/releases/download/v23.11.0-0/Release-23.11.0-0.zip"
        Invoke-WebRequest -Uri $url -OutFile "poppler.zip"
        Expand-Archive -Path "poppler.zip" -DestinationPath "poppler"
        Move-Item -Path "poppler\*" -Destination "poppler-xx"
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --name=PDF_OCR --windowed --clean `
          --add-data "poppler-xx;poppler-xx" `
          --hidden-import=PyQt6.QtCore `
          --hidden-import=PyQt6.QtGui `
          --hidden-import=PyQt6.QtWidgets `
          main.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF_OCR-Windows-x64
        path: dist/PDF_OCR